### ISSUE TITLE
flutter 설치 가이드

### ISSUE THREAD

**Issue by DaehunGwak** [DaehunGwak/flutter-playground#35]
https://docs.flutter.dev/get-started/install

**Comment by DaehunGwak** [comment]
android studio 설치 에러

Internal error. Please refer to https://issuetracker.google.com/issues/new?component=192708

java.nio.file.AccessDeniedException: /Users/user/Library/Application Support/Google/AndroidStudio2023.3
    at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
    at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
    at java.base/java.nio.file.Files.createDirectory(Unknown Source)
    at com.intellij.openapi.util.io.NioFiles.tryCreateDirectory(NioFiles.java:94)
    at com.intellij.openapi.util.io.NioFiles.createDirectories(NioFiles.java:87)
    at com.intellij.platform.ide.bootstrap.DirectoryLock.lockOrActivate(DirectoryLock.java:145)
    at com.intellij.platform.ide.bootstrap.StartupUtil$lockSystemDirs$result$1.invokeSuspend(main.kt:626)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

-----
Your JRE: 17.0.10+0-17.0.10b1087.21-11572160 aarch64 (JetBrains s.r.o.)
/Applications/Android Studio.app/Contents/jbr/Contents/Home

**Comment by DaehunGwak** [comment]
해결 방법
https://chrisjune-13837.medium.com/bugfix-andriod-studio-%EC%84%A4%EC%B9%98%ED%9B%84-%EC%8B%A4%ED%96%89%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%8A%88-306c1d2d6cd

**Comment by DaehunGwak** [comment]
android studio flutter sdk path

<img width="441" alt="image" src="https://github.com/DaehunGwak/flutter-playground/assets/12469427/250da847-5a67-48a1-bceb-17aff6fae1ac">
